import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const instrument_sans = Instrument_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${instrument_sans.className} flex min-h-screen flex-col items-center justify-between`}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
