import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Footer4 } from "@/components/Footer";

const instrument_sans = Instrument_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Imago Dei",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${instrument_sans.className}`}>
        <NavBar/>
        {children}
        <Footer4/>
      </body>
    </html>
  );
}
